# Generated by Django 5.2.5 on 2025-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='tournamentseries',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название серии'),
        ),
    ]
