# Generated by Django 5.2.5 on 2025-08-27 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_team_name_alter_tournamentseries_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='final_place',
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(choices=[(1, '🥇 1 место'), (2, '🥈 2 место'), (3, '🥉 3 место')])),
                ('achieved_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='ratings.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='ratings.tournament')),
            ],
            options={
                'ordering': ['tournament__date', 'place'],
                'unique_together': {('team', 'tournament')},
            },
        ),
    ]
