# Generated by Django 4.0.5 on 2025-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_gameresult_final_place_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='place',
            field=models.PositiveIntegerField(default=0, verbose_name='Место в турнире'),
        ),
    ]
