# Generated by Django 5.2.5 on 2025-09-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_gameresult_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
