# Generated by Django 4.0.5 on 2025-09-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_delete_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentseries',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Серия турниров', 'verbose_name_plural': 'Серии турниров'},
        ),
    ]
