# Generated by Django 4.0.5 on 2025-09-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_tournamentseries_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentseries',
            options={'verbose_name': 'Серия турниров', 'verbose_name_plural': 'Серии турниров'},
        ),
        migrations.AddField(
            model_name='tournamentseries',
            name='tournament_type',
            field=models.CharField(choices=[('cup', 'Кубковый турнир'), ('regular', 'Обычный турнир')], default='regular', max_length=10, verbose_name='Тип турнира'),
        ),
    ]
