# Generated by Django 4.0.5 on 2025-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_alter_tournamentseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='power',
            field=models.FloatField(default=200, verbose_name='Сила команды'),
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('tournament', 'team')},
        ),
    ]
