# Generated by Django 4.0.5 on 2025-09-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_team_power_alter_gameresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='power',
        ),
    ]
